# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dab61b518d07cb12381ad0318e30a0f55f2edd229ac7d10a3e2f0d1c981c5fdf81c26a0acdffce4da73517fb11651ac5405a2753e8b78a5d8e68f5b770bd395

test:
  secret_key_base: 9a0a4a645f1cba9de25684e7c4715945249e9a532fd91c45a42716c5bbec883d234e8820123b73479db05441a09313b25f415a1e1fa2306508030624a7e691df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
